version: '3'

services:

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    ports:
      - "${ELASTICSEARCH_HTTP_PORT:-9200}:9200"
      - "${ELASTICSEARCH_NETWORK_PORT:-9300}:9300"
    environment:
      cluster.name: "docker-cluster"
      ES_JAVA_OPTS: "${ES_JAVA_OPTS:--Xmx512m -Xms512m}"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limit:
          memory: 1gb
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      cluster.name: "docker-cluster"
      ES_JAVA_OPTS: "${ES_JAVA_OPTS:--Xmx512m -Xms512m}"
      discovery.zen.ping.unicast.hosts: elasticsearch1
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limit:
          memory: 1gb
    volumes:
      - esdata2:/usr/share/elasticsearch/data

volumes:
  esdata1:
  esdata2:
