version: '3'
services:
  auditService:
    environment:
      SSL_KEYSTORE_PATH: /keystore
      SSL_KEYSTORE: tomcat.keystore
      SSL_KEYSTORE_PASSWORD: ${CAF_AUDIT_SERVICE_KEYSTORE_PASS:-changeit}
      SSL_CERT_ALIAS: ${CAF_AUDIT_SERVICE_KEYSTORE_ALIAS:-tomcat}
    volumes:
      - ${CAF_AUDIT_SERVICE_KEYSTORE:-./keystore/.keystore}:/keystore/tomcat.keystore
    ports:
      - "${CAF_AUDIT_SERVICE_PORT_HTTPS:-25081}:8443"
