version: '3'

services:

  auditService:
    environment:
      CAF_ELASTIC_PROTOCOL: "${CAF_ELASTIC_PROTOCOL}"
      CAF_ELASTIC_HOST_VALUES: "${CAF_ELASTIC_HOST_VALUES}"
      CAF_ELASTIC_NUMBER_OF_REPLICAS: "${CAF_ELASTIC_NUMBER_OF_REPLICAS}"
      CAF_ELASTIC_NUMBER_OF_SHARDS: "${CAF_ELASTIC_NUMBER_OF_SHARDS}"
      CAF_ELASTIC_PORT_VALUE: "${CAF_ELASTIC_PORT_VALUE}"
      CAF_ELASTIC_USERNAME: "${CAF_ELASTIC_USERNAME}"
      CAF_ELASTIC_PASSWORD: "${CAF_ELASTIC_PASSWORD}"
    image: cafaudit/prereleases:audit-service-3.9.0-853
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 1536M
        reservations:
          cpus: '0.25'
          memory: 768M
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - "${CAF_AUDIT_SERVICE_PORT}:8080"
