version: '3'

services:

  auditService:
    environment:
      CAF_ELASTIC_HOST_AND_PORT: "${CAF_ELASTIC_HOST_AND_PORT}"
      CAF_ELASTIC_CLUSTER_NAME: "${CAF_ELASTIC_CLUSTER_NAME}"
      CAF_ELASTIC_NUMBER_OF_SHARDS: "${CAF_ELASTIC_NUMBER_OF_SHARDS}"
      CAF_ELASTIC_NUMBER_OF_REPLICAS: "${CAF_ELASTIC_NUMBER_OF_REPLICAS}"
    image: cafaudit/audit-service:3.1.0
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 1536M
        reservations:
          cpus: '0.25'
          memory: 768M
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - "${CAF_AUDIT_SERVICE_PORT}:8080"
