title: Audit
email: caf-audit@hpe.com

description: Audit Description
baseurl: "/documentation"

# Build settings
exclude: ['node_modules']

markdown: kramdown
highlighter: rouge

gems: ['jekyll-coffeescript', 'jekyll-watch', 'jekyll-assets', 'jekyll-paginate']

layouts_dir:  caf-templates/_layouts
data_dir:     caf-templates/_data
includes_dir: caf-templates/_includes

paginate: 5
paginate_path: "/pages/en-us/blog/page:num/"